// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace confrence_booking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911121412_add")]
    partial class add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("confrence_booking.Models.GalleryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GalleryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/uploads/gallery/opening.jpg",
                            TitleAr = "افتتاح المؤتمر السابق",
                            TitleEn = "Previous Conference Opening"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/uploads/gallery/awards.jpg",
                            TitleAr = "تكريم الباحثين الفائزين",
                            TitleEn = "Honoring Winning Researchers"
                        });
                });

            modelBuilder.Entity("confrence_booking.Models.InvitationVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvitationVideos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TitleAr = "الفيديو الترويجي للمؤتمر",
                            TitleEn = "Official Conference Promo Video",
                            VideoUrl = "https://www.youtube.com/watch?v=example1"
                        },
                        new
                        {
                            Id = 2,
                            TitleAr = "دعوة رئيس المؤتمر للباحثين",
                            TitleEn = "Conference Chair Invitation",
                            VideoUrl = "https://www.youtube.com/watch?v=example2"
                        });
                });

            modelBuilder.Entity("confrence_booking.Models.MainTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainTopics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionAr = "مناقشة أحدث تقنيات تعلم الآلة والمعالجة اللغوية.",
                            DescriptionEn = "Discussion on latest ML and NLP advances.",
                            TitleAr = "الذكاء الاصطناعي وتطبيقاته",
                            TitleEn = "Artificial Intelligence Applications"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionAr = "طرق حماية الأنظمة والتشفير الرقمي.",
                            DescriptionEn = "Methods for system protection and cryptography.",
                            TitleAr = "أمن المعلومات والأمن السيبراني",
                            TitleEn = "Cybersecurity & Information Security"
                        });
                });

            modelBuilder.Entity("confrence_booking.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "/uploads/partners/menofia.png",
                            Name = "جامعة المنوفية"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "/uploads/partners/iti.png",
                            Name = "معهد تكنولوجيا المعلومات (ITI)"
                        });
                });

            modelBuilder.Entity("confrence_booking.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("confrence_booking.Models.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/uploads/speakers/speaker1.jpg",
                            NameAr = "د. أحمد علي",
                            NameEn = "Dr. Ahmed Ali",
                            TitleAr = "أستاذ علوم الحاسب",
                            TitleEn = "Computer Science Professor"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/uploads/speakers/speaker2.jpg",
                            NameAr = "د. سارة إبراهيم",
                            NameEn = "Dr. Sarah Ibrahim",
                            TitleAr = "خبيرة هندسة البرمجيات",
                            TitleEn = "Software Engineering Expert"
                        });
                });

            modelBuilder.Entity("confrence_booking.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbstractText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("College")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullPaperFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbstractText = "هذا الملخص يوضح كيفية استخدام الخوارزميات الذكية في التشخيص.",
                            College = 7,
                            Email = "ali.mohamed@example.com",
                            FirstName = "علي",
                            FullPaperFilePath = "/uploads/submissions/paper_1.pdf",
                            LastName = "محمد",
                            Level = "Master Student",
                            PaperTitle = "تطبيقات الذكاء الاصطناعي في الطب",
                            Phone = "01012345678",
                            SubmittedAt = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AbstractText = "دراسة تحليلية لتطوير الأجهزة الطبية باستخدام الحوسبة السحابية.",
                            College = 6,
                            Email = "sara.mahmoud@example.com",
                            FirstName = "سارة",
                            FullPaperFilePath = "/uploads/submissions/paper_2.pdf",
                            LastName = "محمود",
                            Level = "PhD Candidate",
                            PaperTitle = "تطوير الأنظمة المدمجة للخدمات الطبية",
                            Phone = "01187654321",
                            SubmittedAt = new DateTime(2026, 9, 2, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("confrence_booking.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 10, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Instructor = "Eng. Mohamed Hassan",
                            TitleAr = "ورشة عمل: بناء Web API بواسطة .NET 8",
                            TitleEn = "Workshop: Building Web APIs with .NET 8"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 10, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Instructor = "Dr. Mahmoud Khaled",
                            TitleAr = "ورشة عمل: أمن البيانات والـ Cloud",
                            TitleEn = "Workshop: Cloud Data Security"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
